import type { Exercise } from "./workoutGenerator";

export const EXERCISE_POOL: Exercise[] = [
  // --- PUSH ---
  {
    id: "pushup",
    name: "Push-ups",
    category: "push",
    intensity: "medium",
    requiresFloor: true,
    isNoisy: false,
    jointStress: { shoulder: true },
  },
  {
    id: "incline_pushup",
    name: "Incline Push-ups",
    category: "push",
    intensity: "low",
    requiresFloor: false,
    isNoisy: false,
    jointStress: { shoulder: true },
  },
  {
    id: "wall_pushup",
    name: "Wall Push-ups",
    category: "push",
    intensity: "low",
    requiresFloor: false,
    isNoisy: false,
    jointStress: { shoulder: true },
  },
  {
    id: "pike_pushup",
    name: "Pike Push-ups",
    category: "push",
    intensity: "high",
    requiresFloor: true,
    isNoisy: false,
    jointStress: { shoulder: true },
  },

  // --- LEGS ---
  {
    id: "squat",
    name: "Squats",
    category: "legs",
    intensity: "medium",
    requiresFloor: false,
    isNoisy: false,
    jointStress: { knee: true },
  },
  {
    id: "reverse_lunge",
    name: "Reverse Lunges",
    category: "legs",
    intensity: "medium",
    requiresFloor: false,
    isNoisy: false,
    jointStress: { knee: true },
  },
  {
    id: "split_squat",
    name: "Split Squats",
    category: "legs",
    intensity: "medium",
    requiresFloor: false,
    isNoisy: false,
    jointStress: { knee: true },
  },
  {
    id: "wall_sit",
    name: "Wall Sit",
    category: "legs",
    intensity: "low",
    requiresFloor: false,
    isNoisy: false,
    jointStress: { knee: true },
  },
  {
    id: "calf_raises",
    name: "Calf Raises",
    category: "legs",
    intensity: "low",
    requiresFloor: false,
    isNoisy: false,
    jointStress: {},
  },

  // --- CORE ---
  {
    id: "plank",
    name: "Plank",
    category: "core",
    intensity: "low",
    requiresFloor: true,
    isNoisy: false,
    jointStress: {},
  },
  {
    id: "dead_bug",
    name: "Dead Bug",
    category: "core",
    intensity: "low",
    requiresFloor: true,
    isNoisy: false,
    jointStress: {},
  },
  {
    id: "standing_knee_raise",
    name: "Standing Knee Raises",
    category: "core",
    intensity: "low",
    requiresFloor: false,
    isNoisy: false,
    jointStress: {},
  },
  {
    id: "standing_oblique",
    name: "Standing Oblique Crunch",
    category: "core",
    intensity: "low",
    requiresFloor: false,
    isNoisy: false,
    jointStress: {},
  },
  {
    id: "march_hold",
    name: "March Hold",
    category: "core",
    intensity: "medium",
    requiresFloor: false,
    isNoisy: false,
    jointStress: {},
  },

  // --- CONDITIONING ---
  {
    id: "jumping_jacks",
    name: "Jumping Jacks",
    category: "conditioning",
    intensity: "high",
    requiresFloor: false,
    isNoisy: true,
    jointStress: { knee: true },
  },
  {
    id: "low_impact_high_knees",
    name: "Low-Impact High Knees",
    category: "conditioning",
    intensity: "medium",
    requiresFloor: false,
    isNoisy: false,
    jointStress: { knee: true },
  },
  {
    id: "shadow_boxing",
    name: "Shadow Boxing",
    category: "conditioning",
    intensity: "medium",
    requiresFloor: false,
    isNoisy: false,
    jointStress: {},
  },
  {
    id: "step_back_burpee",
    name: "Step-back Burpees",
    category: "conditioning",
    intensity: "high",
    requiresFloor: false,
    isNoisy: false,
    jointStress: { knee: true },
  },

  // --- PULL ---
  {
    id: "superman_hold",
    name: "Superman Hold",
    category: "pull",
    intensity: "low",
    requiresFloor: true,
    isNoisy: false,
    jointStress: {},
  },
  {
    id: "reverse_snow_angels",
    name: "Reverse Snow Angels",
    category: "pull",
    intensity: "low",
    requiresFloor: true,
    isNoisy: false,
    jointStress: { shoulder: true },
  },
  {
    id: "pull_apart_sim",
    name: "Pull-Apart Hold",
    category: "pull",
    intensity: "low",
    requiresFloor: false,
    isNoisy: false,
    jointStress: { shoulder: true },
  },
  {
    id: "elbow_drive",
    name: "Elbow Drive",
    category: "pull",
    intensity: "low",
    requiresFloor: false,
    isNoisy: false,
    jointStress: { shoulder: true },
  },
  {
    id: "isometric_row",
    name: "Row Hold",
    category: "pull",
    intensity: "medium",
    requiresFloor: false,
    isNoisy: false,
    jointStress: { shoulder: true },
  },
];